CREATE PROC FI_SP_IncBeneficiario
    @NOME			VARCHAR (50)	,
    @CPF			VARCHAR(14)		,
	@IDCLIENTE		BIGINT
AS
BEGIN
	INSERT INTO CLIENTES (NOME, CPF, IDCLIENTE) 
	VALUES (@NOME, @CPF, @IDCLIENTE)

	SELECT SCOPE_IDENTITY()
END