CREATE PROC FI_SP_VerificaBeneficiario
	@ID BIGINT,
	@CPF VARCHAR(14)
AS
BEGIN
	IF(ISNULL(@ID,0) = 0)
		SELECT NOME, CPF, IDCLIENTE, ID FROM BENEFICIARIOS WITH(NOLOCK)
	ELSE
		SELECT NOME, CPF, IDCLIENTE, ID FROM BENEFICIARIOS WITH(NOLOCK) WHERE IDCLIENTE = @ID and CPF = @CPF
END